travis:
  secure:
    BINSTAR_TOKEN: m90L87Hbkff54eUePlpd4D285aJcAdkUi5/un+JJrzopNp/yHxLrcE5MZkjT7tOeon6T5RdpLPbP0bcu7b0YXwLeVwWDPgTUq0S7+2AvwV24aRu2lkAby3egHxTYL4HQHqMK2NRiyO0G3cCTqOkYh89wEg5+5oHd31Yi425aPP+GlvZ5IVVmXbAzAu0XTSCLDHei6VOJXIRCLbjP1CpOYNPFQlIV5mMtlgqHEGKjOixMEEErcYJeo3YdokSrKc/edRHNLrImhATXP0tnD6F0jr+TiUZVVe3t3P4f3fEsnhdGStwgniAl5gcrgTCh34cIGXx9xzGbqCJFbcM3hzMKelGMjZif7kZvMRZ06itFgLNvaWJaLJrSgMxUX54S6tw3TCzqHB4mP+x2dAf3P0giXR6w1eqWn/y7u2EAa0XSx8qJP8bTP3Xbbwz3v31PFqfS+/NU8aniaPEwT9a6JpHJC9s/YL4N6FSeFwFbYolbx4AkZZTNM6hLwnBdpaH0S8fAhVv/6HWYGsZbFzM6VvkwDnseF381bwPYzR5OoLEGbtXDmgzn0juU0pOzhzzobAPaEgAYolDBFToedUM+iFYSMHeAucCMGT4EifJfZcK8UoxteZXtocVskcZa+/NpzUmd4PZnuXFFD6UQZOtYr8/JC0sfgX0+oMo1Mrur71flbAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
