appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: gz9V//qKXiVbE0m3DwgSQe8N/lBBrOsPbBqAOTlJGuYbC2zWfr+HN4pYAUjB/B0ACmOmvkPIQd8cATPpp4yiBmC5Y0ZhDiZSEpz1eAPVsGmzTx/2M7MSxeo5qZzfTws49bztKupbUebljzdrCb/4iuBo1TIEdvI5INcWnJMYFUtZnYvpUxJcK8oQer9BAi56Odbm+0PL9rlgBsJHxL/MDIbxk5XZZND0AjIkseg6KCVNai69Ybci2rKmp3cpJds1vMhndqzvQU1TDWF4Zex3DaEUeTvRG+TDqaJKscbLpKnzMlubhoueHFyZiNjjW3nCAPQYQkRtpql3drZEXUkce2XRzZiAwoG1fHogW9kOmzfKBNEfb7hqV3O386OV3woRNKhmGtn7rNYXrb9AxiDNwIdqQymNWpX7ostOOEGcmmc/HC9vbB3PFxFnU2swDRSh7/XmxDXUYb1EWpbyIAGj7rMXLOgC4QC6JF0QPDHkzs3t7MdYt1EizODafOcZSyiThUnZzWwE16VjqFLdIprU/M+wXWSLEe3inDz15WIy4vJDWoXdrmyLmi9Gq7qUhIGYUiVe9+HfXuYk05xyC2fFgBxW+xvIaPp4UIuy4aADFasaf48CWwy7sprh0jz9XIVDzVRcn/NF03YpUuap0ylwFeIymNzfgnjrGfHrDDtWaz4=}
